run:
	mvn clean install
	~/Library/wildfly-18/bin/standalone.sh

install:
	mvn clean install

jboss:
	~/Library/wildfly-18/bin/standalone.sh

jboss-cli:
	~/Library/wildfly-18/bin/jboss-cli.sh

add-user:
	~/Library/wildfly-18/bin/add-user.sh

